### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by ChickenWithACrown** [coltonk9043/Aoba-MC-Hacked-Client#38]
I am on fabric 1.20.4 and i am pressing the keybines and they don't work

**Comment by OsakiTsukiko** [comment]
I think the README is out of date (or sth broke along the way).
A few of the modules listed on the README do not have default key binds (for example, x-ray)
But the Toggle GUI one should work, and you can set keybinds from there. If it doesn't check if you don't have sth overriding the keybinds. 

@coltonk9043 can i have access to edit issues (example name of this issue is kinds bad) THX :)

**Comment by coltonk9043** [comment]
Assuming the issue is resolved. If you run into any more issues lmk!
